### ISSUE TITLE
anyway to add custom character?

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#104]
is any way to add custom or beta characters?
thanks..

**Comment by theBowja** [comment]
yes there is. however it may not be easy to get the format right.
https://github.com/theBowja/genshin-db/blob/c6808528a382c2f70e536578153e95a843f705e4/src/getdata.js#L279
you'll have to manually make an index as well.

I will develop an easier way to add custom data but it may take a long time because I am busy procrastinating.

**Comment by ahmadkeren** [comment]
![Screen Shot 2022-04-05 at 14 47 15](https://user-images.githubusercontent.com/49072140/161704686-92001e0d-01d2-48b5-9186-a4c2688941c8.png)
![Screen Shot 2022-04-05 at 14 48 05](https://user-images.githubusercontent.com/49072140/161704806-fb149f90-f7de-4023-840c-c5
![Uploading Screen Shot 2022-04-
![Screen Shot 2022-04-05 at 14 48 45](https://user-images.githubusercontent.com/49072140/161704964-578aba69-b654-42d4-b103-a354e8ba1d17.png)
05 at 14.48.32.png…]()
10297ed7f2.png)

Excuse me, i successful add new ascend and basic information about a custom character. Then, i try to add details talent about that custom character.. why the result is blank?
Thanks

**Comment by ahmadkeren** [comment]
Am i missing something?

**Comment by ahmadkeren** [comment]
SOLVED, i forgot put stats for that talent
![Screen Shot 2022-04-06 at 04 49 56](https://user-images.githubusercontent.com/49072140/161855558-2207f4a7-7f9c-4ff9-b10d-99725603328d.png)
