### ISSUE TITLE
Is it possible to query across languages?

### ISSUE THREAD

**Issue by meimisaki** [theBowja/genshin-db#11]
It seems the following example is not supported by the current implementation: 😢 

```js
genshindb.characters('Amber', {
    querylanguages: ['english'],
    resultlanguage: 'japanese',
});
```

Since the query string `Amber` cannot be located in the name list of `src/index/japanese/characters.json`. I believe this is a relatively common usage, we might need a primary key to track objects among different languages. (for example, always put english name in the aliases field may help 😃)

**Comment by theBowja** [comment]
I'm pretty sure I already coded it in a way such that it can query across multiple languages. However I've currently restricted it to English since there's actually no data for other languages.

You can add query/result support by adding 'japanese' (folder name) to design.json and adding relevant data into that folder. Make sure to fill out as much of japanese/categories.json as you can. Keep all property names for all data the same as in English.

**Comment by theBowja** [comment]
I haven't actually tested it so tell me if it still isn't working

**Comment by meimisaki** [comment]
> I haven't actually tested it so tell me if it still isn't working. The code that actually combines the indexes of all the querylangs is in main.js:buildQueryDict(querylangs).

I haven't actually tested it either, lol. I just read the codes, and tried to emulate the execution in my mind. I apologize if I did something wrong.

> Since the query string Amber cannot be located in the name list of src/index/japanese/characters.json

By that I mean, even if we full-filled data in `src/japanese` folder, the example above still won't work:
- input query `Amber`, note this keyword never appears in `src/japanese` folder, instead `アンバー` does
- the `autocomplete` function keeps it identical
- [this line](https://github.com/theBowja/genshin-db/blob/d2933c9eee7d524807f7682f5b4c74877d1082df/src/main.js#L95) would fail to find the query in the name list

After a hard fighting in spiral abyss, I'm gonna sleep now. I might do an actual test after I wake up today. 😴

**Comment by theBowja** [comment]
If you have querylanguages: ['english'], then it will search through only the English index. This is how it should work. It won't search 'Amber' in the Japanese index at all.

```
genshindb.characters('Amber', {
    querylanguages: ['japanese'],
    resultlanguage: 'japanese',
});
```
If you do this, then it won't be able to find anything since Amber is not in the Japanese index. You can search in multiple indexes instead.

```
genshindb.characters('Amber', {
    querylanguages: ['english', 'japanese'],
    resultlanguage: 'japanese',
});
```
This will go through both indexes. It'll match and get the string 'amber.json' from the English index. Then it will try and find 'amber.json' in the Japanese folder and return that data.

**Comment by meimisaki** [comment]
> It'll match and get the string 'amber.json' from the English index. Then it will try and find 'amber.json' in the Japanese folder and return that data.

How could `amber.json` get matched as it [always being filtered](https://github.com/theBowja/genshin-db/blob/d2933c9eee7d524807f7682f5b4c74877d1082df/src/main.js#L68)? Again, as I mentioned above, `autocomplete` has no effect to a correct spelling, even if you put both english and japanese in the query languages.

> The 'primary key' that you mentioned originally is the file name, which isn't queryable.

I finally get your point, the data in different languages share the same filename, so we could take the filename from one language, and retrieve it in another. While the code doesn't seem to reflect your idea, so let me demonstrate you the whole query process line by line, and show you the issue:

First sanitize options:
```js
opts = Object.assign({}, baseoptions, sanitizeOptions(opts));
// { querylanguage: ['english', 'japanese'], resultlanguage: 'japanese', ... }
```

And build query dict:
```js
const dict = buildQueryDict(opts.querylanguages, folder);
// ['Aether', 'Amber', ..., 'Geo', 'Snezhnaya', 'Polearm', 'アンバー', ...]
```

Then autocomplete the query:
```js
query = autocomplete(""+query, dict);
// 'Amber'
```

Next, load index from `index/japanese/characters.json`, here 空 and アンバー are the japanese names of Aether and Amber respectively:
```js
const queryindex = getJSON(`index/${opts.resultlanguage}/${folder}.json`);
// { names: ['空', 'アンバー', ...], file: ['aether.json', 'amber.json', ...], ... }
```

After that, locate the query string `Amber` in the name list:
```js
const nameindex = queryindex.names.indexOf(query)
// -1
```

Finally, we failed to find `Amber` and return nothing:
```js
const filename = queryindex.file[nameindex];
// undefined
```

It only takes a few lines to fix the issue, iterate over **all query languages**, not only the **result language**, try to locate the query string in corresponding index, then everything will be fine.

PS. the issue may persist in filtering mode, while that's another story:
```js
genshindb.characters('Ballad', {
    querylanguages: ['english', 'japanese'],
    resultlanguage: 'japanese',
});
```

**Comment by theBowja** [comment]
Ooh I see the problem. I autocomplete across all query languages but I failed to grab the filename across all query languages.

**Comment by theBowja** [comment]
Couldn't really find a clean solution for the category values.  We have to make sure that japanese/categories.json is getting translated 1-to-1 from english/categories.json. Basically the values in the arrays can't move around.

On the other hand I could've looped through a querydict from each querylanguage to figure out what language the query got autocompleted in... but whatever I just did works fine so whatever.

As usual, I won't look into performance since I don't think anyone would actually run my code from a potato.
