### ISSUE TITLE
Bennett is registered as a Claymore

### ISSUE THREAD

**Issue by Ephrem-Adugna** [theBowja/genshin-db#22]
Hi, I've been using this library for a while now, and it's been great. The only thing I would add is that bennett is registered as a claymore, not sword, user.

**Comment by theBowja** [comment]
What version or language are you using? I'm not seeing this error.

**Comment by Ephrem-Adugna** [comment]
I'm using nodejs. I installed it using npm

**Comment by theBowja** [comment]
What version is the genshin-db library you are using? You can find this in your package.json file.

What function and query are calling that you are getting bennett claymore?

**Comment by Ephrem-Adugna** [comment]
I'm using version ^1.12.5, and I'm calling it using genshin.characters('bennett')

**Comment by theBowja** [comment]
The library is currently on v3.1.0 and it's already fixed there. You'll have to update to a new version.

You can do that by doing:
npm install genshin-db@latest

Be careful though because there's been a lot of changes and the format of the data output may be different from what you're using. Check out the examples file for the latest format https://github.com/theBowja/genshin-db/blob/main/examples.md.

**Comment by Ephrem-Adugna** [comment]
Wow, all this data is amazing, thank you so much, I had no idea I was missing out on this haha
