### ISSUE TITLE
Yanfei material

### ISSUE THREAD

**Issue by pcyli** [theBowja/genshin-db#24]
Just noticed yanfei's character data is missing the talent material type. Should be gold. Do you want me to issue a pull request to fix that?

**Comment by theBowja** [comment]
You are welcome to make a pull request to fix this. I think Rosaria and Eula are probably also missing their talentmaterialtype. I didn't automate talentmaterialtype yet because I haven't figured out how to handle it for different languages.
Just make your changes to the data/English/characters files and do `npm run assemble` at the root of the project before committing.

I'm planning on fixing some missing image links over the weekend before releasing a new patch.

**Comment by theBowja** [comment]
fixed in latest release
